In [1]:
import numpy as np
import pandas as pd

In [2]:
# load growth function parameters from Butzin and Pörtner, 2016
# 2do: specify your own path to the growth function file
grofup = np.load('gmorhua_growth_function_2018.npz')
a_fit = grofup['a_fit'][::5]              # note: the original temperature increment       
b_fit = grofup['b_fit'][::5]              # underlying a_fit and b_fit is 0.1 K
c_avg = grofup['c_avg']

In [30]:
np.savetxt('growth_function_parameters_simple.csv', np.array([a_fit,b_fit]).astype('float64'), delimiter=',', fmt='%.6f')

In [6]:
c_avg

array(0.29100703)

In [5]:
#print(grofup['a_fit'])

In [42]:
max_age = 15 * 365                        # maximum age in days
weight_at_age = np.zeros((max_age, 65))      # weight at age (in g) for a given temperature
weight_at_age[0, :] = 1                   # initial weight in g
dt = 1                                    # time step in days
itemp = 0                                 # temperature index

In [44]:
# loop over temperatures, increasing values by 0.5°C
for tempc in np.arange(-2,30.5,0.5):           # Temperature range in °C
    #print ("Temperature (°C): ", tempc)
    for age in np.arange(1, max_age):
        
        growth_rate = 0.01 * (a_fit[itemp] * weight_at_age[age - 1, itemp] ** b_fit[itemp] - c_avg)
        weight_at_age[age,itemp] = weight_at_age[age - 1, itemp] * (1. + dt * growth_rate)
    itemp = itemp + 1

In [51]:
len(np.arange(-2,30.5,.5))

65

In [49]:
# convert numpy array to pandas dataframe
# index column = days
# columns header = temperatures in °C

df = pd.DataFrame(
    weight_at_age, index=[np.arange(1, max_age + 1)], 
    columns=np.arange(-2,30.5,.5).astype('str')
)

df.index.name = 'Day'
print(df.head())

       -2.0      -1.5      -1.0      -0.5       0.0       0.5       1.0  \
1  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
2  1.002131  1.002784  1.003517  1.004338  1.005258  1.006287  1.007437
3  1.004265  1.005573  1.007042  1.008690  1.010537  1.012604  1.014914
4  1.006402  1.008367  1.010576  1.013055  1.015835  1.018949  1.022433
5  1.008541  1.011166  1.014118  1.017433  1.021154  1.025324  1.029992

        1.5       2.0       2.5  ...      25.5      26.0      26.5      27.0  \
1  1.000000  1.000000  1.000000  ...  1.000000  1.000000  1.000000  1.000000
2  1.008718  1.010143  1.011726  ...  1.055746  1.053646  1.051606  1.049626
3  1.017492  1.020363  1.023555  ...  1.112401  1.108082  1.103892  1.099835
4  1.026323  1.030660  1.035487  ...  1.169940  1.163285  1.156841  1.150610
5  1.035211  1.041035  1.047523  ...  1.228342  1.219236  1.210432  1.201934

       27.5      28.0      28.5      29.0      29.5      30.0
1  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
2  1.047709  1.045855  1.044063  1.042334  1.040666  1.039059
3  1.095913  1.092125  1.088470  1.084947  1.081554  1.078288
4  1.144596  1.138795  1.133208  1.127829  1.122654  1.117679
5  1.193742  1.185854  1.178264  1.170968  1.163958  1.157226

[5 rows x 65 columns]

In [10]:
df

,-2,-1.5,-1,-0.5,0,0.5,1,1.5,2,2.5,...,25.5,26,26.5,27,27.5,28,28.5,29,29.5,30
1,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
2,1.002131,1.002784,1.003517,1.004338,1.005258,1.006287,1.007437,1.008718,1.010143,1.011726,...,1.055746,1.053646,1.051606,1.049626,1.047709,1.045855,1.044063,1.042334,1.040666,1.039059
3,1.004265,1.005573,1.007042,1.008690,1.010537,1.012604,1.014914,1.017492,1.020363,1.023555,...,1.112401,1.108082,1.103892,1.099835,1.095913,1.092125,1.088470,1.084947,1.081554,1.078288
4,1.006402,1.008367,1.010576,1.013055,1.015835,1.018949,1.022433,1.026323,1.030660,1.035487,...,1.169940,1.163285,1.156841,1.150610,1.144596,1.138795,1.133208,1.127829,1.122654,1.117679
5,1.008541,1.011166,1.014118,1.017433,1.021154,1.025324,1.029992,1.035211,1.041035,1.047523,...,1.228342,1.219236,1.210432,1.201934,1.193742,1.185854,1.178264,1.170968,1.163958,1.157226
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5471,26.429880,50.296746,92.350956,163.599932,279.688846,461.662617,736.225148,1135.172147,1693.707682,2447.474062,...,90.467402,77.131201,66.085874,56.897591,49.220573,42.778326,37.348995,32.753936,28.848772,25.516395
5472,26.432647,50.302422,92.361793,163.619385,279.721893,461.715995,736.307416,1135.293482,1693.879341,2447.707492,...,90.467408,77.131205,66.085877,56.897593,49.220574,42.778327,37.348996,32.753936,28.848773,25.516395
5473,26.435413,50.308096,92.372626,163.638830,279.754925,461.769350,736.389648,1135.414761,1694.050915,2447.940803,...,90.467414,77.131209,66.085880,56.897594,49.220576,42.778328,37.348996,32.753936,28.848773,25.516395
5474,26.438178,50.313768,92.383454,163.658267,279.787945,461.822681,736.471842,1135.535982,1694.222404,2448.173994,...,90.467420,77.131213,66.085882,56.897596,49.220577,42.778328,37.348997,32.753937,28.848773,25.516396
5475,26.440943,50.319438,92.394279,163.677697,279.820950,461.875990,736.553999,1135.657146,1694.393809,2448.407065,...,90.467426,77.131217,66.085885,56.897598,49.220578,42.778329,37.348997,32.753937,28.848773,25.516396